import 'package:flutter/material.dart';
import 'package:flutter_news/part2/content1/HomeItemListPage.dart';

List<Widget> tabContents = [
//  RecentPage(),
  HomeItemListPage(),
  Center(
    child: Text('头条'),
  ),
  Text('视频'),
  Text('娱乐'),
  Text('体育'),
  Text('新时代'),
  Text('要闻'),
  Text('段子'),
  Text('知否'),
  Text('上海'),
  Text('公开课'),
  Text('圈子'),
  Text('财经'),
  Text('科技'),
  Text('汽车'),
  Text('网易号'),
  Text('军事'),
  Text('时尚'),
  Text('跟帖'),
  Text('直播'),
  Text('图片'),
  Text('小视频'),
  Text('NBA'),
  Text('热点'),
  Text('房产'),
  Text('股票'),
  Text('轻松一刻'),
  Text('历史'),
  Text('家居'),
  Text('播单'),
  Text('独家'),
  Text('游戏'),
  Text('健康'),
  Text('航空'),
  Text('小说'),
  Text('热度'),
];
